apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guardrail

resources:
  - namespace.yaml
  - core-deployment.yaml
  - services.yaml
  - dashboard.yaml

commonLabels:
  app.kubernetes.io/part-of: guardrail-alpha
