//! Market-data commands: a live/mock market table, AMM-style swap quotes,
//! classic technical indicators over a deterministic price series, an attention
//! watchlist, and pool liquidity capacity. These read from the CMC data path
//! (live REST when keyed, deterministic mock otherwise).

use crate::util::{cost_bps, decimal_from_str, gas_cost_usd, json_decimal_or};
use crate::DEFAULT_UNIVERSE;
use common::decimal::to_f64;
use common::Settings;
use rust_decimal::Decimal;
use std::str::FromStr;

/// Default HTTP timeout (ms) for the live CMC REST client.
const CMC_TIMEOUT_MS: u64 = 10_000;

/// Print a live market table for the eligible universe.
///
/// With `--live` and `CMC_API_KEY` set, pulls from the real CMC REST API;
/// otherwise falls back to the deterministic mock (and says so).
pub fn run_markets(config: &str, live: bool) -> anyhow::Result<()> {
    let _settings = Settings::load(config)?;
    let universe = market_data::Universe::load(DEFAULT_UNIVERSE)?;

    let runtime = tokio::runtime::Runtime::new()?;
    runtime.block_on(async {
        // Pick a data source: live REST when requested and keyed, else mock.
        let source: Box<dyn cmc_client::CmcDataSource> = match (live, std::env::var("CMC_API_KEY"))
        {
            (true, Ok(api_key)) if !api_key.is_empty() => {
                Box::new(cmc_client::CmcRestClient::new(api_key, CMC_TIMEOUT_MS)?)
            }
            (true, _) => {
                println!("note: --live requested but CMC_API_KEY is not set; using mock data");
                Box::new(cmc_client::MockCmcClient::new())
            }
            (false, _) => Box::new(cmc_client::MockCmcClient::new()),
        };

        let snapshot = market_data::SnapshotBuilder::new(source.as_ref(), &universe)
            .build()
            .await?;

        match &snapshot.fear_greed {
            Some(fg) => println!("Fear & Greed: {} ({})", fg.value, fg.classification),
            None => println!("Fear & Greed: unavailable"),
        }
        println!();

        println!(
            "{:<8} | {:>14} | {:>8} | {:>16} | {:>16} | {:>6}",
            "SYMBOL", "PRICE", "24H%", "VOL_24H", "LIQUIDITY", "SAFETY"
        );
        println!("{}", "-".repeat(82));

        for a in &snapshot.assets {
            let ret_24h = a
                .ret_24h
                .map(|r| format!("{:>8.2}", to_f64(r)))
                .unwrap_or_else(|| format!("{:>8}", "n/a"));
            let liquidity = a
                .liquidity_usd
                .map(|l| format!("{:>16.2}", to_f64(l)))
                .unwrap_or_else(|| format!("{:>16}", "n/a"));

            println!(
                "{:<8} | {:>14.6} | {} | {:>16.2} | {} | {:>6}",
                a.asset.symbol,
                to_f64(a.price_usd),
                ret_24h,
                to_f64(a.volume_24h_usd),
                liquidity,
                a.safety_score,
            );
        }

        Ok::<(), anyhow::Error>(())
    })?;

    Ok(())
}

pub fn run_quote(from: &str, to: &str, amount: &str) -> anyhow::Result<()> {
    let amount = Decimal::from_str(amount)
        .map_err(|_| anyhow::anyhow!("amount must be a number, got '{amount}'"))?;
    // AMM-style quote against a nominal pool.
    let pool = Decimal::from(3_000_000);
    let slippage = backtester::slippage::estimate_pct(amount, pool);
    let expected_out = (amount * (Decimal::ONE - slippage / Decimal::from(100))).round_dp(2);

    let quote = serde_json::json!({
        "from": from,
        "to": to,
        "amount_in_usd": amount.to_string(),
        "expected_out_usd": expected_out.to_string(),
        "slippage_pct": slippage.to_string(),
        "venue": "twak/pancakeswap",
    });
    println!("{}", serde_json::to_string_pretty(&quote)?);
    Ok(())
}

/// Fear/greed level used when evolving the deterministic indicator price path.
const INDICATOR_FEAR_GREED: u32 = 60;

/// Build a deterministic close-price series and print latest indicator values.
///
/// The series is generated by evolving `backtester::synthetic::initial_price`
/// with `step_return_24h_pct`, so output is reproducible for a given symbol and
/// step count. Indicators are computed over the resulting closes.
pub fn run_indicators(symbol: &str, steps: u32) -> anyhow::Result<()> {
    if steps == 0 {
        anyhow::bail!("steps must be greater than 0");
    }

    // Evolve a deterministic price path into a series of closes.
    let mut price = backtester::synthetic::initial_price(symbol);
    let mut closes: Vec<f64> = Vec::with_capacity(steps as usize);
    for step in 0..steps {
        let r = backtester::synthetic::step_return_24h_pct(symbol, step, INDICATOR_FEAR_GREED);
        price *= Decimal::ONE + r / Decimal::from(100);
        closes.push(to_f64(price));
    }

    let latest_close = closes
        .last()
        .copied()
        .ok_or_else(|| anyhow::anyhow!("no closes generated"))?;

    // Compute the classic indicator set over the closes.
    let ema_series = indicators::ema(&closes, 12);
    let sma_series = indicators::sma(&closes, 12);
    let rsi_series = indicators::rsi(&closes, 14);
    let macd_out = indicators::macd(&closes, 12, 26, 9);
    let bb = indicators::bollinger(&closes, 20, 2.0);

    /// Format the last value of a series, or `n/a` when empty/insufficient data.
    fn last_fmt(series: &[f64]) -> String {
        series
            .last()
            .map(|v| format!("{v:.6}"))
            .unwrap_or_else(|| "n/a".to_string())
    }

    println!("# Indicators · {symbol}");
    println!();
    println!("steps: {steps} · fear/greed: {INDICATOR_FEAR_GREED}");
    println!();
    println!("latest close : {latest_close:.6}");
    println!("EMA(12)      : {}", last_fmt(&ema_series));
    println!("SMA(12)      : {}", last_fmt(&sma_series));
    println!("RSI(14)      : {}", last_fmt(&rsi_series));
    println!(
        "MACD(12,26,9): line={} signal={} hist={}",
        last_fmt(&macd_out.macd),
        last_fmt(&macd_out.signal),
        last_fmt(&macd_out.histogram),
    );
    println!(
        "Bollinger(20,2.0): upper={} mid={} lower={}",
        last_fmt(&bb.upper),
        last_fmt(&bb.mid),
        last_fmt(&bb.lower),
    );

    Ok(())
}

pub fn run_watchlist(limit: usize) -> anyhow::Result<()> {
    let limit = limit.clamp(1, 50);
    let universe = market_data::Universe::load(DEFAULT_UNIVERSE)?;
    let runtime = tokio::runtime::Runtime::new()?;
    let mut rows = runtime.block_on(async {
        let source = cmc_client::MockCmcClient::new();
        let snapshot = market_data::SnapshotBuilder::new(&source, &universe)
            .build()
            .await?;
        let mut rows = Vec::new();
        for asset in snapshot.assets {
            if asset.asset.category.is_stable() {
                continue;
            }
            let ret_24h = asset.ret_24h.map(to_f64).unwrap_or(0.0);
            let volatility = asset.volatility_1h.map(to_f64).unwrap_or(0.0);
            let liquidity = asset.liquidity_usd.map(to_f64).unwrap_or(0.0);
            let safety_penalty = ((100_i64 - asset.safety_score as i64).max(0) as f64) / 10.0;
            let liquidity_penalty = if liquidity > 0.0 && liquidity < 500_000.0 {
                8.0
            } else {
                0.0
            };
            let flag_penalty = asset.security_flags.len() as f64 * 6.0;
            let score = ret_24h.abs()
                + (volatility * 2.0)
                + safety_penalty
                + liquidity_penalty
                + flag_penalty;
            let status = if score >= 25.0 {
                "critical"
            } else if score >= 12.0 {
                "watch"
            } else {
                "normal"
            };
            rows.push((
                asset.asset.symbol,
                format!("{:?}", asset.asset.category).to_ascii_lowercase(),
                status.to_string(),
                score,
                ret_24h,
                volatility,
                liquidity,
                asset.safety_score,
            ));
        }
        anyhow::Ok(rows)
    })?;
    rows.sort_by(|a, b| b.3.partial_cmp(&a.3).unwrap_or(std::cmp::Ordering::Equal));
    rows.truncate(limit);

    println!("# Watchlist");
    println!();
    println!("limit: {limit}");
    println!("| Symbol | Category | Status | Score | 24h % | Vol % | Liquidity | Safety |");
    println!("|:-------|:---------|:-------|------:|------:|------:|----------:|-------:|");
    for (symbol, category, status, score, ret_24h, volatility, liquidity, safety) in rows {
        println!(
            "| {:<6} | {:<14} | {:<8} | {:>5.2} | {:>5.2} | {:>5.2} | {:>9.0} | {:>6} |",
            symbol, category, status, score, ret_24h, volatility, liquidity, safety
        );
    }
    Ok(())
}

pub fn run_liquidity(policy_path: &str, limit: usize) -> anyhow::Result<()> {
    let policy = crate::read_json_report(policy_path)
        .ok_or_else(|| anyhow::anyhow!("failed to read liquidity policy {policy_path}"))?;
    let universe_path = policy
        .get("universe_path")
        .and_then(serde_json::Value::as_str)
        .unwrap_or(DEFAULT_UNIVERSE);
    let max_usage = json_decimal_or(&policy, "max_pool_usage_pct", Decimal::new(5, 1));
    let warning_usage = json_decimal_or(&policy, "warning_pool_usage_pct", Decimal::new(35, 2));
    let min_liquidity = json_decimal_or(&policy, "min_liquidity_usd", Decimal::from(500_000));
    let notional = json_decimal_or(&policy, "default_order_notional_usd", Decimal::from(1000));
    let universe = market_data::Universe::load(universe_path)?;
    let runtime = tokio::runtime::Runtime::new()?;
    let mut rows = runtime.block_on(async {
        let source = cmc_client::MockCmcClient::new();
        let snapshot = market_data::SnapshotBuilder::new(&source, &universe)
            .build()
            .await?;
        let mut rows = Vec::new();
        for asset in snapshot.assets {
            if asset.asset.category.is_stable() {
                continue;
            }
            let liquidity = asset.liquidity_usd.unwrap_or(Decimal::ZERO);
            let capacity = liquidity * max_usage / Decimal::from(100);
            let usage = if liquidity > Decimal::ZERO {
                notional / liquidity * Decimal::from(100)
            } else {
                Decimal::ZERO
            };
            let headroom = (capacity - notional).max(Decimal::ZERO);
            let status = if liquidity < min_liquidity || usage > max_usage {
                "blocking"
            } else if usage >= warning_usage {
                "watch"
            } else {
                "ok"
            };
            rows.push((
                asset.asset.symbol,
                status.to_string(),
                liquidity,
                capacity,
                usage,
                headroom,
            ));
        }
        anyhow::Ok(rows)
    })?;
    rows.sort_by_key(|a| a.5);
    rows.truncate(limit.clamp(1, 50));

    println!("# Liquidity");
    println!();
    println!("policy: {policy_path}");
    println!("notional_usd: {:.2}", notional);
    println!("max_pool_usage_pct: {:.4}", max_usage);
    println!();
    println!("| Symbol | Status | Liquidity | Capacity | Usage % | Headroom |");
    println!("|:-------|:-------|----------:|---------:|--------:|---------:|");
    for (symbol, status, liquidity, capacity, usage, headroom) in rows {
        println!(
            "| {:<6} | {:<8} | {:>9.2} | {:>8.2} | {:>7.4} | {:>8.2} |",
            symbol, status, liquidity, capacity, usage, headroom
        );
    }
    Ok(())
}

pub fn run_costs(config_path: &str, amount_override: Option<&str>) -> anyhow::Result<()> {
    let config = crate::read_json_report(config_path)
        .ok_or_else(|| anyhow::anyhow!("failed to read cost config {config_path}"))?;
    let native_price = json_decimal_or(&config, "native_price_usd", Decimal::from(610));
    let gas_price_gwei = json_decimal_or(&config, "gas_price_gwei", Decimal::from(3));
    let quote_gas = json_decimal_or(&config, "quote_gas_units", Decimal::from(45_000));
    let swap_gas = json_decimal_or(&config, "swap_gas_units", Decimal::from(210_000));
    let approval_gas = json_decimal_or(&config, "approval_gas_units", Decimal::from(65_000));
    let approval_required = config
        .get("approval_required")
        .and_then(serde_json::Value::as_bool)
        .unwrap_or(true);
    let amount = amount_override
        .and_then(decimal_from_str)
        .unwrap_or_else(|| {
            json_decimal_or(&config, "default_order_notional_usd", Decimal::from(1000))
        });
    let gas_units = quote_gas
        + swap_gas
        + if approval_required {
            approval_gas
        } else {
            Decimal::ZERO
        };
    let gas_usd = gas_cost_usd(gas_units, gas_price_gwei, native_price);
    let pool = Decimal::from(3_000_000);
    let slippage_pct = backtester::slippage::estimate_pct(amount, pool);
    let slippage_usd = (amount * slippage_pct / Decimal::from(100)).round_dp(4);
    let route_count = config
        .get("routes")
        .and_then(serde_json::Value::as_array)
        .map(Vec::len)
        .unwrap_or(0);

    println!("# Execution Costs");
    println!();
    println!("config: {config_path}");
    println!(
        "chain: {}",
        config
            .get("chain")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("bsc")
    );
    println!("amount_usd: {:.2}", amount);
    println!(
        "gas_price_gwei: {:.2} · native_price_usd: {:.2}",
        gas_price_gwei, native_price
    );
    println!();
    println!("| Route | Gas USD | Slippage USD | All-In USD | Cost BPS |");
    println!("|:------|--------:|-------------:|-----------:|---------:|");
    if let Some(routes) = config.get("routes").and_then(serde_json::Value::as_array) {
        for route in routes {
            let from = route
                .get("from")
                .and_then(serde_json::Value::as_str)
                .unwrap_or("USDT");
            let to = route
                .get("to")
                .and_then(serde_json::Value::as_str)
                .unwrap_or("WBNB");
            let all_in = gas_usd + slippage_usd;
            println!(
                "| {}->{} | {:>7.4} | {:>12.4} | {:>10.4} | {:>8.2} |",
                from,
                to,
                gas_usd,
                slippage_usd,
                all_in,
                cost_bps(all_in, amount)
            );
        }
    }
    println!();
    println!(
        "routes: {route_count} · total_gas_usd: {:.4} · total_slippage_usd: {:.4}",
        gas_usd * Decimal::from(route_count as i64),
        slippage_usd * Decimal::from(route_count as i64)
    );
    Ok(())
}
