mod agent_card;
mod agent_services;
mod assets;
mod audit_manifest;
mod backtest;
mod bnb_sdk;
mod briefing;
mod budget;
mod cmc_capabilities;
mod commerce;
mod compete;
mod compile;
mod costs;
mod drift;
mod ensemble;
mod ensemble_live;
mod exit_triggers;
mod experiments;
mod exposure;
mod funding;
mod heartbeat;
mod history;
mod indicators;
mod job_simulator;
mod journal;
mod liquidity;
mod mandates;
mod optimize;
mod playbook;
mod presets;
mod prizes;
mod quotes;
mod rebalance;
mod regime;
mod routes;
mod scenarios;
mod scorecard;
mod sdk_catalog;
mod proof_verify;
mod server;
mod signing_policy;
mod snapshots;
mod skill;
mod skill_detail;
mod stream;
mod skills;
mod sweep;
mod ta;
mod trending;
mod version;
mod walkforward;
mod wallet_controls;
mod watchlist;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    observability::tracing_setup::init();
    version::init_uptime();
    server::serve("0.0.0.0:8080").await
}
